name: Deploy Node.js project to function app

on:
  push:
    branches:
      - "master"

env:
  AZURE_FUNCTIONAPP_NAME: blog-server
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "dist"
  NODE_VERSION: "20.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies Using Npm"
        shell: bash
        run: |
          npm install
          npm run build --if-present
          npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_URL: ${{ secrets.AZURE_STORAGE_URL }}

      - name: "Show deployment folder size and contents"
        run: |
          du -sh ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          ls -lR ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
